# Generated by Django 3.0.14 on 2023-06-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('ProducPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Department', models.CharField(max_length=200)),
            ],
        ),
    ]
