version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb

  web:
    build: .
    command: >
      bash -c "echo Aguardando o PostgreSQL... && while !</dev/tcp/db/5432; do sleep 1; done &&
      python manage.py makemigrations RiHappyApi &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
